name: "Manage PostgreSQL database for your Dokku Application"
author: "Sébastien Lacoste-Seris"
description: "Setting an environment variable during dokku deployment action."
branding:
  icon: "database"
  color: "green"
inputs:
  ssh-private-key:
    description: "The ssh private key to the dokku instance. WARNING: use a secret! Do not pass a plain text value!"
    required: true
  dokku-user:
    description: "The user to use for ssh (Default: dokku)"
    required: false
    default: "dokku"
  dokku-host:
    description: "The dokku host to ssh into"
    required: true
  app-name:
    description: "The dokku app name"
    required: true
  db-name:
    description: "The name of the database to be deployed"
    required: true
  destroy:
    description: "The value of the environment variable to set in dokku config (Default: false)"
    required: true
    default: false
  aws-access-key-id:
    description: "AWS access key id"
    required: false
  aws-region:
    description: "AWS Region"
    required: false
  aws-secret-access-key:
    description: "AWS secret access key"
    required: false
  s3-data-load:
    description: "The S3 file name to import into the DB"
    required: false
  backup-s3:
    description: "The backup activation to an existing S3 bucket"
    required: false
  backup-s3-bucket:
    description: "The S3 bucket name used for backup"
    required: false
  backup-s3-schedule:
    description: "The S3 bucket name used for backup"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.ssh-private-key }}
    - ${{ inputs.dokku-user }}
    - ${{ inputs.dokku-host }}
    - ${{ inputs.app-name }}
    - ${{ inputs.db-name }}
    - ${{ inputs.destroy }}
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-region }}
    - ${{ inputs.s3-data-load }}
    - ${{ inputs.backup-s3 }}
    - ${{ inputs.backup-s3-bucket }}
    - ${{ inputs.backup-s3-schedule }}
