name: test
on: workflow_dispatch

jobs:
  create:
    runs-on: [ubuntu-latest, self-hosted, dev]
    steps:
    - uses: ./
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        dokku-host: ${{ secrets.DOKKU_HOST }}
        app-name: myapp
        db-name: mydb
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
        s3-data-load: "s3://enloya-db/next.pgdump"

  destroy:
    runs-on: [ubuntu-latest, self-hosted, dev]
    needs: [create]
    steps:
    - uses: ./
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        dokku-host: ${{ secrets.DOKKU_HOST }}
        app-name: myapp
        db-name: mydb
        destroy: true
